export enum PokemonType {
  FIRE = 'FIRE',
  WATER = 'WATER',
  ELECTRIC = 'ELECTRIC',
  STONE = 'STONE',
  FIGHTER = 'FIGHTER',
  GRASS = 'GRASS',
  NORMAL = 'NORMAL',
  PSYCHIC = 'PSYCHIC',
  POISON = 'POISON',
}
